name: CI

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        smalltalk: [ Moose64-13 ]
    name: ${{ matrix.smalltalk }}
    steps:
      - uses: actions/checkout@v4

      - uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}

      - name: Run tests
        shell: bash
        run: smalltalkci -s ${{ matrix.smalltalk }}
        timeout-minutes: 15


      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}