name: CI

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        smalltalk: [ Moose64-12 ]
    name: ${{ matrix.smalltalk }}
    steps:
      - uses: actions/checkout@v4

      - name: Move tree-sitter lib
        shell: bash
        run: |
          cd ressources/lib
          sudo mv libtree-sitter-v0.25.3.so /usr/local/lib/libtree-sitter.so
          cd ../..
      
      - name: Move C lib grammar
        shell: bash
        run: |
          cd ressources/lib
          sudo mv libtree-sitter-c-v0.25.3.so /usr/local/lib/libtree-sitter-c.so
          cd ../..

      - uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}

      - name: Run tests
        shell: bash
        run: smalltalkci -s ${{ matrix.smalltalk }}
        timeout-minutes: 15


      # - name: Coveralls
      #   uses: coverallsapp/github-action@master
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}